# @package _global_


training:
  lr_schedule_type: "step"
  lr_schedule_config:
    gamma: 0.85
    step_size: 10
    min_lr: null
    warmup_epochs: 0          # number of epochs to warm up (0 disables)
    warmup_init_lr: 0.0      # start LR for warmup